{
 "title": "FastAPI Metrics",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Latency p50",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 7, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 14, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Latency p99",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 21, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))"
    }
   ]
  }
 ]
}