global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8001']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
