global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8001']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
