name: CD

on:
  push:
    tags:
      - '*'

env:
  API_TAG: ${{ github.ref_name }}
  FRONT_TAG: ${{ github.ref_name }}
  REGISTRY: ${{ secrets.REGISTRY_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push backend
        run: |
          docker build -t $REGISTRY/backend:$API_TAG backend
          docker push $REGISTRY/backend:$API_TAG
      - name: Build and push frontend
        run: |
          docker build -t $REGISTRY/frontend:$FRONT_TAG frontend
          docker push $REGISTRY/frontend:$FRONT_TAG
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            pwsh ./scripts/deploy_prod.ps1 `
              -Registry ${{ env.REGISTRY }} `
              -Username ${{ secrets.REGISTRY_USER }} `
              -Password ${{ secrets.REGISTRY_PASSWORD }} `
              -EnvFilePath ${{ secrets.ENV_FILE_PATH }} || `
            pwsh ./scripts/rollback.ps1 `
              -EnvFilePath ${{ secrets.ENV_FILE_PATH }}
