name: CI

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r backend/requirements.txt
      - run: pytest -q
        working-directory: backend
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
        working-directory: frontend
      - run: npm run build
        working-directory: frontend
  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t ghcr.io/${{ github.repository }}/backend:latest backend
      - run: docker build -t ghcr.io/${{ github.repository }}/frontend:latest frontend
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker push ghcr.io/${{ github.repository }}/backend:latest
      - run: docker push ghcr.io/${{ github.repository }}/frontend:latest
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/coulisses
            docker compose pull
            docker compose --profile prod up -d
